### ISSUE TITLE
IRIS causes Z-Fighting with non-existant texture on monitors, Shaders causes either crash or non-existant displays

### ISSUE THREAD

**Issue by Merith-TK** [cc-tweaked/cc-restitched#1]
## Useful information to include:
 - Minecraft: 1.17.1
 - CC: Restitched: 1.97.0-alpha
 - Detailed reproduction steps: 
 
![](https://cdn.discordapp.com/attachments/851534220680495165/896538828674830356/unknown.png)
![](https://cdn.discordapp.com/attachments/851534220680495165/896540046079963176/unknown.png)
Shaders can cause crash, I have had it happen once, and can no longer open the world due to the rendering issue

**Comment by KoromaruKoruko** [comment]
My Suggestion, Update the Render code to use the fabric render API.
as the issue is likely caused by directly interfacing with OpenGL.

**Comment by TheNukeLore** [comment]
any fix on this such issue? its been a decent while and iris has picked up a lot of steam

**Comment by Merith-TK** [comment]
Actually one is in the works! but for 1.18 only,
download the latest github actions 
and set the computercraft-client.toml file to use VBO instead of BEST

https://github.com/cc-tweaked/cc-restitched/actions/runs/1749267785

**Comment by Merith-TK** [comment]
Closed in favor of #34
