### ISSUE TITLE
run computers clientside to reduce latencey in high ping cenarios

### ISSUE THREAD

**Issue by Virusnest** [cc-tweaked/cc-restitched#106]
Read the title

**Comment by toad-dev** [comment]
If they ran client-side on a 8 person server, whose client would a given computer run on? All of them? How would the server resolve situations where the clients get out of sync? Would the constant syncing of state both up and down really result in lower latency?

Computers don't exist in a vacuum. They _are_ part of the server game logic: computers need to access and mutate the game state during execution, other bits of game logic need to know about what computers are doing (turtles move around and have inventories!), and computers have state that needs to be synced to all players. I don't think client-side computers make much sense.

**Comment by Merith-TK** [comment]
while the single client would show low latency the problem would arise as Toad Dev stated, how would it sync across multiple users on an server? also such an feature would break parity with logic from CC:T anyways, which for CC:R (outside of netherite tools which somehow made it in there) is against the main goal of CC:R, which is to be as 1:1 as possible with CC:T.
