### ISSUE TITLE
quilt server on 1.18.2 seems to have no config file for the mod (we're looking to increase storage limits)

### ISSUE THREAD

**Issue by hellholesys** [cc-tweaked/cc-restitched#110]
## Useful information to include:
 - Minecraft version: Quilt Server 1.18.2 (exact loader version unknown) with QFAPI 1.0.0-beta.19 and QSL 1.1.0-beta.17
 - CC: Restitched version: 1.100.6 (as shipped with the blanketcon pack, as the server is an smp not affiliated with bc or quilt using the pre-ceremony (aka public) world download)
 - Logs: n/a

## the problem
the config folder has no config file for cc, which is a problem as we want to increase storage limits so we can store lots of things on our computers since we intend for this server to be a thing many people use, and want to make sure that we (the people running the server) and all the other players can store everything they need

## steps to reproduce
- set up the blanketcon 2022 pack for a server using packwiz
- start the server
- look in the config folder at the root of the server folder
- there is no config file there (the expected behavior is for there to be a filled out config file, ready to be edited so that the mod functions in the needed way)

**Comment by Merith-TK** [comment]
the server config for CC is located in `/world/serverconfig/`

the only config that is in `/config` is the client config and barely has any use outside of changing what rendering method monitors should use, which doesnt need to be touched for the most part

**Comment by hellholesys** [comment]
oh-
i mainly play on 1.12.2 so im used to the way that things work there
im gonna go edit it now
thanks

**Comment by Merith-TK** [comment]
No worries! you might find quite an few mods use serverconfig as well!
