### ISSUE TITLE
pastebin

### ISSUE THREAD

**Issue by RandomTNT** [cc-tweaked/cc-restitched#113]
pastebin not downloading shit

## Useful information to include:
 - Minecraft version 1.19
 - CC: Restitched version 1.101.0 
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.
  - Please send `latest.log` AND the appropriate crashlog,
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed. try to use any pastebin command to download any shit

**Comment by Merith-TK** [comment]
not enough information, please provide more info such as 

*the bloody logs*
this will allow us to see what mods you are using in conjuction, 

Server IP, (some servers might block pastebin)
`saves/<world>/serverconfig/comptercraft.toml`, (pastebin might be blocked here)
etc,

screenshots with this command setup
```
clear
ls
pastebin get <your paste> <filename>
ls
```
