### ISSUE TITLE
Turtle refuses to equip items

### ISSUE THREAD

**Issue by Nebdir** [cc-tweaked/cc-restitched#116]
## Useful information to include:
 - Minecraft version: 1.19
 - CC: Restitched version: 1.101.0
## expected behaviour
turtle equips given item
## actual behaviour
any item is refused with not an valid upgrade,
tried with cobblestone, a wooden pickaxe and an stone hammer of Fabricae Ex Nihilo
## Detailed reproduction steps
1. place a turtle
2. place any item in inventory slot 1, tested with 2 also
3. run `equip 1 left` or `2 left` or `1 right` or `2 right`
4. equipping is refused

## additional
I've searched through the logs and found only an issues about chunk saving with cc and that my audio device is not available (no reference to cc call stack).

just ask if you like to get the stacktraces, the full log is more or less useless as the error about my audio device is repeated over and over . neverless I would provide it if asked.

If this is the intended behaviour I would like to request to change that to allow other items to be equipped and used to break blocks.

**Comment by toad-dev** [comment]
This sounds like expected behavior. The only valid turtle tools are the
vanilla diamond tools, and they must be non-enchanted and undamaged to
equip. Can you check that a brand new diamond pickaxe equips?

**Comment by Nebdir** [comment]
Equiping an diamond tool just works fine.

Therefor please take this as a feature request. Let turtles equip other tools, buckets would be cool too.

This might intersect the goal to maintaine the original functionality of cc. Still i think that this would be a good addition, same goes with rightclick.

Should i open a seperate feature request for those and close this, as this is currently the intended behaviour?

**Comment by Merith-TK** [comment]
This is currently the intended behavior, CC:R attempts to maintain as close to 1:1 parity with CC:T, so an feature like that would have to be made on CC:T's repo.

The only time we have really strayed from true pairity is the textures, and the fact that we somehow allowed netherite tools to be equiped to turtles for some reason/somehow

**Comment by toad-dev** [comment]
> Should i open a seperate feature request for those and close this, as this is currently the intended behaviour?

Can you open a new issue with the feature request? It would be nice to have somewhere for people to see and discuss this request because it comes up often.

The usual answer is that equipping arbitrary modded tools could easily be overpowered, and so it would be better suited to an optional add-on mod. But it would still be interesting if we could get fresh discussion on this feature, if only to help inspire somebody to actually make that mod :P

**Comment by Nebdir** [comment]
opened cc-tweaked/cc-tweaked#1135, as this is the base of this fork I think it's better to discuss it there.
