### ISSUE TITLE
[bug] Chest reports 1billion getItemLimit in modded environment

### ISSUE THREAD

**Issue by ShreksHellraiser** [cc-tweaked/cc-restitched#120]
## Useful information to include:
 - Minecraft version: 1.19
 - CC: Restitched version: 1.101.0
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor. N/A
  - Please send `latest.log` AND the appropriate crashlog, N/A
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

Calling getItemLimit on a vanilla chest results in 1000000000 returned. From the documentation I'd expect 64
![Screenshot_20220727_224604](https://user-images.githubusercontent.com/70228812/181409150-0da7f034-04da-455f-be3b-1cbccdc19ed3.png)
.

**Comment by Merith-TK** [comment]
can you also show the output of `a.list()`?

and are you playing with any other mods?
—Merith

**Comment by Merith-TK** [comment]
with the current info, I am unable to recreate the issue
![image](https://user-images.githubusercontent.com/10422110/181411538-cdebff87-ec7b-4572-acef-b16c84c38a61.png)

**Comment by ShreksHellraiser** [comment]
![image](https://user-images.githubusercontent.com/70228812/181411799-5fb33fd3-b552-4383-a3e8-54cdb006c6c9.png)
I am playing with many other mods. I should've tested this with just CC:R before submitting an issue, sorry for that.

**Comment by Merith-TK** [comment]
No worries! its always an good idea to test both, so then we can narrow down which mods cause problems! so we can figure out why that problem came to be, and fix it!

**Comment by ShreksHellraiser** [comment]
https://pastebin.com/cC424nyp
Here's the modlist, it's quite extensive. I think it might be caused by the Reinforced series (Reinforced Barrels, Chests, and Shulkers). I'm going to test with just those mods and report my findings

**Comment by Merith-TK** [comment]
(ignore my screenshots, I didnt notice this was 1.19)

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/181413555-818d35f6-4dc5-4272-8f74-e6a09bc92caf.png)
yeah still not able to re-create issue, must be conflict with another mod...

**Comment by ShreksHellraiser** [comment]
Hmm, I've just tested this with the Reinforced Series alone, and it reports the proper size. I'm not sure what other mods could be causing it.

**Comment by ShreksHellraiser** [comment]
Since this isn't a CC:R issue I'll close this, I'll see about trying to find the actual culprit
