### ISSUE TITLE
`os.epoch("ingame")` errors with `Unsupported operation`

### ISSUE THREAD

**Issue by ouroborus** [cc-tweaked/cc-restitched#123]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

The [CC:Tweaked docs](https://tweaked.cc/module/os.html#v:epoch) lists `"ingame"`, `"utc"`, and `"local"` as valid argument values. However, `os.epoch("ingame")` results in an error, `"Unsupported operation"`.

**Comment by ouroborus** [comment]
Verified with 1.101.2 in 1.19.2

**Comment by Merith-TK** [comment]
can you test with the build from #126 ?

**Comment by ouroborus** [comment]
@Merith-TK Confirmed fixed
