### ISSUE TITLE
Quilt - Blockstates endless loop in initialization

### ISSUE THREAD

**Issue by ehre0004** [cc-tweaked/cc-restitched#125]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

**Info**:
- **Minecraft version**: 1.19.2
- **Modloader**: Quilt 0.17.4
- **Quilted Fabric API**: 4.0.0-beta.10+0.60.0-1.19.2
- **Pastebin**: [https://pastebin.com/RbcErCEM](https://pastebin.com/RbcErCEM)

**Summary**:
I seem to be stuck in an endless loop of rebuilding blockstates in loading the game. It was necessary to kill the instance. Another mod that does this is Farmer's Delight. See snippet below:
> [10:08:27] [Render thread/WARN]: Rebuilding BlockStates! Someone accessed BlockStates ids too early...
> [10:08:27] [Render thread/WARN]: Called by:
> 	net.minecraft.class_2361.handler$dka000$polymer_moveToEnd(class_2361.java:1066)
> 	net.minecraft.class_2361.method_10205(class_2361.java)
> 	net.minecraft.class_2246.md58ccf7$lambda$onInit$0$1(class_2246.java:1169)
> 	com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
> 	net.minecraft.class_2246.md58ccf7$lambda$onInit$1$0(class_2246.java:1167)
> 	net.minecraft.class_2378.md58ccf7$lambda$new$0$4(class_2378.java:3154)
> 	net.minecraft.class_2370.handler$enj000$quilt$invokeEntryAddEvent(class_2370.java:4112)
> 	net.minecraft.class_2370.method_31051(class_2370.java:130)
> 	net.minecraft.class_2370.method_10273(class_2370.java:87)
> 	net.minecraft.class_2348.method_10273(class_2348.java:24)
> 	net.minecraft.class_2370.method_10272(class_2370.java:135)
> 	net.minecraft.class_2378.method_39197(class_2378.java:508)
> 	net.minecraft.class_2378.method_10230(class_2378.java:504)
> 	dan200.computercraft.shared.Registry$ModBlocks.register(Registry.java:98)
> 	dan200.computercraft.shared.Registry$ModBlocks.<clinit>(Registry.java:102)
> 	dan200.computercraft.shared.Registry$ModBlockEntities.<clinit>(Registry.java:173)
> 	dan200.computercraft.shared.Registry.init(Registry.java:80)
> 	dan200.computercraft.ComputerCraft.onInitialize(ComputerCraft.java:120)
> 	java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
> 	jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy51.onInitialize(Unknown Source)
> 	org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
> 	org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
> 	org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
> 	org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
> 	org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)

**Notes**:
I have disabled mods that seem to have similar issues. If even 1 of these mods are active, loading is impossible.
Game loads successfully when aforementioned mods are disabled.

Also, sorry if I missed some key info. I am new to reporting.

**Comment by MarioAndWeegee3** [comment]
This looks like the same bug as [this issue](https://github.com/Patbox/polymer/issues/41); it should be fixed in the latest Polymer update

**Comment by Patbox** [comment]
Yep, it's not cc-restiched issue. Please install latest version of polymer library: https://github.com/Patbox/polymer/#download
