### ISSUE TITLE
MixinLangauge breaks Vanilla translations on Quilt servers

### ISSUE THREAD

**Issue by Gaming32** [cc-tweaked/cc-restitched#132]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

I haven't tested on 1.19, but `MixinLanguage` does not appear to have changed.

## Reproduction

1. Install a Quilt server
2. Install QFAPI and CC:R
3. Run the server

## Logs

[Logs](https://mclo.gs/xd1DtJ8)
You can see that it says "menu.preparingSpawn" instead of "Preparing spawn area".

**Comment by Merith-TK** [comment]
Odd, We unfortunately need that mixin otherwise modded items, when `inspect`ed will return their translation key rather than their name,

**Comment by Gaming32** [comment]
This has been fixed in Quilt Loader 0.18.1-beta.10.
