### ISSUE TITLE
How do i create a server using CC: Restiched

### ISSUE THREAD

**Issue by PaxtonPenguin** [cc-tweaked/cc-restitched#145]
### Minecraft Version

1.19.x

### Version

1.102.0

### Details

This Isn't really a bug, but i want to use cc: restiched on my minecraft server. It says "Client and Server" on the modrinth page which makes me think that its also server side, but no, it isn't.

So... How?

**Comment by Merith-TK** [comment]
the term "Client and Server" on modrinth means that it is required on *both*

if your looking for an purely serverside version, look for the Polymer Port made by Patbox on modrinth, 

HOWEVER, if you are on Fabric 1.19.4, I would advise you use the latest CC:Tweaked Fabric released today 4 hours ago
https://modrinth.com/mod/cc-tweaked/version/1.19.4-1.104.0
