### ISSUE TITLE
Monitors getting very dark with sodium

### ISSUE THREAD

**Issue by timuzkas** [cc-tweaked/cc-restitched#148]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

When i was trying to do my stuff with monitors, i noticed that they were very dark. Now  And when in pitch up gamma, monitors brightness gets normal. But not all of the players in that server has gamma changed, so they dont see text on monitors.

**Comment by Merith-TK** [comment]
can you please send logs? Also if you are on 1.19.4, please use CC:T (it has fabric now!)

**Comment by object-Object** [comment]
@Merith-TK We're also experiencing this. It only happens with both Sodium and Iris (yeah, it's Iris again), not just Sodium. It also breaks differently depending which renderer is selected in the CC:R config. We're on 1.19.2, so CC:T isn't an option.
Logs: https://mclo.gs/3XkZPgj

VBO / Best:
![2023-05-27_16 08 33](https://github.com/cc-tweaked/cc-restitched/assets/37044997/c847c2ce-e6d0-450a-a32e-53adf0dd72fc)

TBO:
![2023-05-27_16 08 16](https://github.com/cc-tweaked/cc-restitched/assets/37044997/55c50634-a6e8-4292-96e5-47536ff999da)
In that second image, only the center monitor actually has anything written to it. Moving around makes the text on all of them disappear depending where I'm standing.

**Comment by Merith-TK** [comment]
@Patbox any chance ye back port over the MAD rendering method from CC:Polymer to CC:R for this? it seems newer versions of iris+sodium are breaking things...
Context, the MAD renderer is some black magic Patbox did to make monitors render server side, (client sees MapArt, hence MapArtDisplay, MAD)


Can you try adding Indium to see if that helps? @object-Object

**Comment by object-Object** [comment]
We have Indium in [our pack](https://github.com/HexxyCraft/modpack) already, so apparently it doesn't.

**Comment by Minenat69** [comment]
I have the same issue with Sodium Iris and Indium. I hope this can be fixed soon this issue doesn't make me want to dig deeper in this mod...

**Comment by Minenat69** [comment]
@Timasbro How did you managed to correct this locally ?

**Comment by NickSeagull** [comment]
Getting same thing over here, running AQM2

**Comment by SquidDev** [comment]
See also https://github.com/IrisShaders/Iris/issues/1959 - this appears to be an upstream Iris bug. It's reported as fixed, but I'm not sure it was fixed completely.
