### ISSUE TITLE
Further Development

### ISSUE THREAD

**Issue by WillowMist** [cc-tweaked/cc-restitched#149]
With the Fabric development on Tweaked starting up with 1.19.3+, will any further updates be done to Restitched?  Create mod hasn't moved past 1.19.2 and I'm trying to work out how to make the Item Vaults work as a generic storage peripheral.

**Comment by Merith-TK** [comment]
Look at UnlimitedPeripheralWorks, https://modrinth.com/mod/unlimitedperipheralworks/version/1.19.2-0.2.6

**Comment by WillowMist** [comment]
That looks perfect.  I see that it requires CC:T, will it work with CC:R?

EDIT: Looks like it does :)

**Comment by Merith-TK** [comment]
1.19.2 releases should work with CC:R as CC:T fabric is currently 1.19.4
only

**Comment by WillowMist** [comment]
Now I might be trying to implement some changes to the 1.19.2 branch of PeripheralWorks. :)
