### ISSUE TITLE
fromBlit not working

### ISSUE THREAD

**Issue by vuyghu2020** [cc-tweaked/cc-restitched#152]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

The fromBlit function dose not work and says that it is a nil value

**Comment by Merith-TK** [comment]
Which minecraft version specifically? 
And can you show screenshots from CC:Tweaked and CC:Restitched (you can just swap the mod and modloader with the same world)

**Comment by vuyghu2020** [comment]
oh it did not work on eather of them i thought that it did not work for CC: Restitched anly but colors.toBlit work

**Comment by Merith-TK** [comment]
Since you can reproduce this bug on CC:T, please reopen the issue there
https://github.com/cc-tweaked/CC-Tweaked/issues

**Comment by SquidDev** [comment]
[`colours.fromBlit`](https://tweaked.cc/module/colors.html#v:fromBlit) was added in CC:T 1.105.0, and so is only available for Minecraft 1.19.4 and later (and 1.4.7 :D). I'm afraid it won't be present on any 1.18.x version.
