### ISSUE TITLE
getting list() from item vault create does not work

### ISSUE THREAD

**Issue by Nold0r** [cc-tweaked/cc-restitched#153]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

hi, I have a problem getting data from the item vault mod create, when I try to get a list of items from the vault, I get nil.
I am using CC: Restitched on version 1.19.2 and UnlimitedPeripheralWorks is also installed
here is my code :
```local chest =  peripheral.find("create:item_vault")
local groupedItems = {}
for i, itemChest in pairs(chest.list()) do 
    local mod, name = itemChest.name:match("([^:]+):([^:]+)")
    if groupedItems[mod] then
        if (groupedItems[mod])[name]then
            (groupedItems[mod])[name] = (groupedItems[mod])[name] + itemChest.count
        else
            (groupedItems[mod])[name] =  itemChest.count
        end
    else
        groupedItems[mod] = {[name] = itemChest.count}
    end

end
print(textutils.serialise(groupedItems))
```
the code gets a list of items from the repositories and converts this list into a new sorted one, and then simply outputs a table with the new list to the terminal

**Comment by Merith-TK** [comment]
Create utilizes a different storage API than the common slot-based one everything else uses

UnlimitedPeripheralWorks implements the ItemStorage API so that it can be used, (I think it works on normal chests as well even)f
https://docs.siredvin.site/API/item_storage/

**Comment by Merith-TK** [comment]
Your code
![image](https://github.com/cc-tweaked/cc-restitched/assets/10422110/39116914-ed98-444d-9746-a387a02af7eb)

Adjusted to use `items` instead of `list`
![image](https://github.com/cc-tweaked/cc-restitched/assets/10422110/912c6191-35b1-4c99-b955-fd6d9bb24134)
