### ISSUE TITLE
Computer GUI doesn't resize in multiplayer.

### ISSUE THREAD

**Issue by TheArcaneBrony** [cc-tweaked/cc-restitched#16]
## Useful information to include:
 - Minecraft version: 1.17.1
 - CC: Restitched version: 
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor. - n/a
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.
1) increase gui size on server
2) join server
3) open computer

### Singleplayer:
https://cdn.discordapp.com/attachments/299683192091443201/905920847292817488/unknown.png

### Multiplayer:
https://cdn.discordapp.com/attachments/299683192091443201/905920461022589009/unknown.png

**Comment by SkyTheCodeMaster** [comment]
Here is a picture that you forgot to include :p
![image](https://user-images.githubusercontent.com/34724753/140417794-121409f8-5106-489f-abde-23a2ae66eeba.png)

**Comment by TheArcaneBrony** [comment]
included now, together with single player
