### ISSUE TITLE
Netherite Pickaxe Mining Turtle missing name in English Language file

### ISSUE THREAD

**Issue by Wiggles1305** [cc-tweaked/cc-restitched#17]
## Version Info:
 - 1.17.1
 - CC: Restitched 1.97.1-beta

## How to reproduce:
 - Craft any kind of turtle with a Netherite Pickaxe
## How to fix this:
 - This can be fixed by adding some kind of adjective for the Netherite Pickaxe Mining Turtle under the language files.

I would do this myself but I have no idea how to edit the repository

**Comment by Wiggles1305** [comment]
![2021-11-10_18 18 38](https://user-images.githubusercontent.com/46032650/141226803-f8955833-8a69-4957-b717-154df713ca68.png)
Here's an image I forgot to add.

**Comment by Merith-TK** [comment]
huh, okay well if you fork the repo, you will notice in our readme, we have
a card that shows that we are `gitpod ready-to-code`, if you open the repo
in gitpod, (you will have to change the url in the readme card to your
fork), it will give you a bare bones setup for the repo to poke around,
edit, and even compile to download and test changes and fixes! it
doesn't stack up to something locally installed like intellij, but it gets
the job done for small things like this.

i hope that helps! I am currently busy with life atm so any assistance in
development would be very much appreciated!
—Merith
