### ISSUE TITLE
Computers restart on terrain unload

### ISSUE THREAD

**Issue by sneik15** [cc-tweaked/cc-restitched#18]
The computers reboot and stop running the current program when you move far enough away from them to unload the terrain and return to where they are.

## Useful information to include:
 - Minecraft version: 1.17.1
 - CC: Restitched version: v1.97.1-beta-1
 - Detailed reproduction steps: Place any type of computer, move about 1000 blocks away from it and come back.

**Comment by SquidDev** [comment]
This is expected behaviour and how CC has always worked. We're trying to improve it but it's tricky - see https://github.com/cc-tweaked/CC-Tweaked/issues/535 for more details.
