### ISSUE TITLE
1.18 support? when?

### ISSUE THREAD

**Issue by addidotlol** [cc-tweaked/cc-restitched#29]
Since 1.18 came out about 8 days ago I'm hoping this gets updated soon. I would love to use it on my server.

**Comment by Merith-TK** [comment]
1.18 is currently in progress! Trust me i run a server as well, according to the people who are working on the 1.18 port, the main thing that is being problematic are monitors, but I think they almost have that done? maybe a week at most? dont take my word for an acurate timeline however.

**Comment by addidotlol** [comment]
> 1.18 is currently in progress! Trust me i run a server as well, according to the people who are working on the 1.18 port, the main thing that is being problematic are monitors, but I think they almost have that done? maybe a week at most? dont take my word for an acurate timeline however.

oh thank you! I do lots of stuff regarding computercraft so I can't wait to be able to play with it soon

**Comment by Merith-TK** [comment]
We now have an alpha for 1.18 out! please go ahead and test it!
