### ISSUE TITLE
[1.18.X] Iris breaking monitors? Look here!

### ISSUE THREAD

**Issue by Merith-TK** [cc-tweaked/cc-restitched#34]
## Status Codes
 - Complete: Everything works
 - Works: iris "works", may have a bug or two, and may require a work around or two by player.
 - Broken: Unplayable bug, but can be worked around/tolerated by player
 - Borked: Unplayable bug, cannot be worked around by player, requires new release with patched code
 
## Minecraft 1.18.1
 - Status: Works
 - Workaround for flickering monitor
   - alter `computercraft-client.toml` to use `VBO` instead of `BEST` or `TBO` in configs
 
## Minecraft 1.18.2
 - Status: Borked
 - Known Issues, 
   - [Entities/Block Entities render through monitors](https://github.com/cc-tweaked/cc-restitched/issues/34#issuecomment-1067459404)
   - [Block Entities rendering is just borked](https://github.com/cc-tweaked/cc-restitched/issues/34#issuecomment-1068491251)

**Comment by Eklip5e** [comment]
the problem still exists on 1.18.1, w/CC:Restitched ver 1.100.1
yes, i have iris and to make it "work" i have to turn off shaders which makes the monitor flicker every sec

**Comment by Merith-TK** [comment]
`.minecraft/config/computercraft-client.toml`
change `BEST` to `VBO`
—Merith

**Comment by GlowingUmbreon** [comment]
Changing from `BEST` to `VBO` fixes them to what I consider a usable state but I am still experiencing some interesting effects.
![image](https://user-images.githubusercontent.com/37640997/158286290-adce3538-91f0-4361-8bea-2a6373535c52.png)
It appears transparent thing and entities render ontop of the monitors.

**Comment by Merith-TK** [comment]
uhm... are you using the latest release? the latest release *should have the fixes* for iris, unless they broke it


still need to use VBO, as we basically had VBO rewritten for iris compatibility

**Comment by GlowingUmbreon** [comment]
I am using the latest release 1.100.3

**Comment by GlowingUmbreon** [comment]
![image](https://user-images.githubusercontent.com/37640997/158475830-cf5880dd-514b-4324-bfab-967d0855d640.png)
Looks like the monitor effects other things as well.

The causes of this are really weird, if I place a chest in the same chunk as the monitor on the same or below Y level as the *PC* then this effect disappears.

**Comment by Merith-TK** [comment]
hmm, looks like 1.18.2 broke shit again lol, will have someone look at it
