### ISSUE TITLE
Mod listed as 1.18 compatible in curseforge loader when its for 1.18.1

### ISSUE THREAD

**Issue by Infor-Master** [cc-tweaked/cc-restitched#35]
## Useful information to include:
 - 1.18
 - CC: Restitched version
 - Logs: 
 

> net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'CC:Restitched' (computercraft) 1.99.1 (C:\Users\rodri\Twitch\Minecraft\Instances\Performance+ (1) (1)\mods\cc-restitched-1.99.1.jar) with any version that is compatible with:
		 - minecraft 1.18
Unmet dependency listing:
	 - Mod 'CC:Restitched' (computercraft) 1.99.1 requires version 1.18.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18!
		 - 'Minecraft' (minecraft) 1.18 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'CC:Restitched' (computercraft) 1.99.1, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Cloth Utils v1' (cloth-utils-v1) 2.0.54, reason: inactive parent mod (nested jar)
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'CC:Restitched' (computercraft) 1.99.1 (C:\Users\rodri\Twitch\Minecraft\Instances\Performance+ (1) (1)\mods\cc-restitched-1.99.1.jar) with any version that is compatible with:
		 - minecraft 1.18
Unmet dependency listing:
	 - Mod 'CC:Restitched' (computercraft) 1.99.1 requires version 1.18.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18!
		 - 'Minecraft' (minecraft) 1.18 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'CC:Restitched' (computercraft) 1.99.1, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Cloth Utils v1' (cloth-utils-v1) 2.0.54, reason: inactive parent mod (nested jar)
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more

 - Detailed reproduction steps: found mod in curse forge launcher as being 1.18 compatible. Added it and game obviouly crashed. As the log sugests its only 1.18.1 compatible, wich means the mod is tagged wrongly in curseforge.

**Comment by Infor-Master** [comment]
![image](https://user-images.githubusercontent.com/55793949/146575037-05ef495d-1ce8-4e0d-94a7-c33a8f9b8713.png)

**Comment by Infor-Master** [comment]
modifying the dependencies in "fabric.mod.json" inside the .jar where it says 

`"minecraft": "1.18.1"`

 to 

`"minecraft": "1.18"`

seems to fix it and not only does the mod load but it also works. Needs further testing but id say its an easy fix to implement

**Comment by toad-dev** [comment]
The hard dependency on 1.18.1 is deliberate due to [security issues](https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition) with 1.18. Please update to 1.18.1 if you can!

**Comment by Infor-Master** [comment]
i am aware, and i do use the recomended java rguments for that reason but the mod still appears in curseforge as 1.18. If its 1.18.1 then it should be modified accordingly.

**Comment by Merith-TK** [comment]
I will fix this in about 30 ish minutes on the curseforge,

**Comment by Merith-TK** [comment]
just fixed it
