### ISSUE TITLE
CC breaks multiple mod pipes

### ISSUE THREAD

**Issue by bobstar3233** [cc-tweaked/cc-restitched#37]
If CC is on server it breaks server boot as listed in a previous bug report.
but if its still on client and you connect to a server it makes pipes hidden and glitchy to stand on
Cables tested
AE2
Modern Industrialisation 

Im sure theres others if you want to talk more about it my discord is: bobstar8283#6969

**Comment by toad-dev** [comment]
What version did you test with? And can you tell me at least one mod that is affected so I can go about debugging this?

**Comment by bobstar3233** [comment]
can confirm the update you just gave me to issue #36  has seemed to fix it

**Comment by toad-dev** [comment]
Okay glad the hear it!
