### ISSUE TITLE
Multiple wired speakers can't play at the same time

### ISSUE THREAD

**Issue by dewrot** [cc-tweaked/cc-restitched#4]
## Useful information to include:
 - Minecraft version --> 1.16.5
 - CC: Tweaked version -- 1.94.1-beta
 - Detailed reproduction steps: Simply have more than one speaker on a modem network. https://forums.computercraft.cc/index.php?topic=345

**Comment by Merith-TK** [comment]
bug does not exist in 1.17 builds
