### ISSUE TITLE
[1.17.1]Game crashes after activating redstone piston

### ISSUE THREAD

**Issue by PedroExpedito** [cc-tweaked/cc-restitched#43]
### Minecraft Version

1.17.x

### java 

openjdk 16

### Version

cc 1.97.3

## How to reproduce 

use a common redstone piston and lever and activate. Ready the game crashes

### fabric-api-0.44.0+1.17

[latest.log](https://github.com/cc-tweaked/cc-restitched/files/7746261/latest.log)

[crash-2021-12-20_12.19.53-server.txt](https://github.com/cc-tweaked/cc-restitched/files/7746255/crash-2021-12-20_12.19.53-server.txt)

**Comment by SquidDev** [comment]
I think this might be another instance of #32. @Toad-Dev, do we want/need to backport that fix to 1.17?

**Comment by toad-dev** [comment]
Testing it now to be sure. I'll push the fix here in a minute.

**Comment by Merith-TK** [comment]
Try using Java 17, new versions of the fabric api require it (because the fabric devs said so)

**Comment by PedroExpedito** [comment]
@Toad-Dev Toad-Dev  after the commit worked, thank you very much
you can close the issue if you want.
