### ISSUE TITLE
Download link for CC:Restitched Downloads a Zero length jar

### ISSUE THREAD

**Issue by phillipinman** [cc-tweaked/cc-restitched#44]
Hi,

Just wanted to let you know the download link on modrinth downloads a zero length file for some reason, not entirely sure if this is their platform or the uploaded file but just wanted to mention it :)

The link in question:
https://cdn.modrinth.com/data/eldBwa5V/versions/1.99.1/cc-restitched-1.99.1.jar

Also many thanks for porting and maintaining a fabric build, really appreciate it :)

Cheers,

**Comment by Merith-TK** [comment]
Yeah thats not supposed to happen lol
Give me a second to fix it!

**Comment by Merith-TK** [comment]
Okay yeah i think modrinth is just *not liking* that version
Anyways need to push a new version with a crash-fix anyways!

**Comment by Merith-TK** [comment]
https://modrinth.com/mod/cc-restitched/version/cqqkoXt4
