### ISSUE TITLE
Chests bug out on using 1.17.1 saves in 1.18

### ISSUE THREAD

**Issue by AmbitiousAlan** [cc-tweaked/cc-restitched#49]
### Minecraft Version

1.18.x

### Version

V1.99.1-1.18.x

### Details

![unknown](https://user-images.githubusercontent.com/18636088/147579029-731f525f-bdbb-4e79-b901-7810f6a43016.png)

I played on 1.17.1 using cc:restitched (with other mods).

I tried transferring my saves from 1.17.1 to 1.18.1 but there were two issues. One issue is unrelated to this mod, but the other issue is that chests seems to be bugging out. But not all chests. Only chests that were in particular chunks. So, I looked at what these chunks had that other chunks did not: computers/turtles. 

To test my hypothesis, I walked a bit outside my home and placed two chests in different chunks. One chest had a computer in the chunk with it. The test confirmed my hypothesis (see the picture attached).

Personally, I will go through the hassle of just removing all computers/turtles and see if that fixes it. My code is all on Atom and computers are cheap to make (and even if they weren't, I could just spawn an equal amount back).

However, maybe this is worth fixing for others.

**Comment by AmbitiousAlan** [comment]
The 1.17.1 version of the mod was v1.97.2

**Comment by AmbitiousAlan** [comment]
They also bug out other blocks such as beds. However, breaking the invisible bed and placing it back fixes it.
Chests loses all their content.

**Comment by toad-dev** [comment]
> To test my hypothesis, I walked a bit outside my home and placed two chests in different chunks. One chest had a computer in the chunk with it. The test confirmed my hypothesis

Can I get a clarification on this test? Did you place these chests while running 1.17 and then switch to 1.18 and see the bugged behavior? Or does this bug happen in worlds even post 1.17->1.18 transition (like you did this test on 1.18 and immediately saw the bugged chests)?

**Comment by AmbitiousAlan** [comment]
"Did you place these chests while running 1.17 and then switch to 1.18 and see the bugged behavior? "
Yes. Exactly. 
"Or does this bug happen in worlds even post 1.17->1.18 transition (like you did this test on 1.18 and immediately saw the bugged chests)?" No. I hadn't done that test, but now I did. Everything seems fine at first glance if you start from 1.18. 

The problem also removes text from signs (and makes them invisible). Makes brewing stance invisible and also deletes their content. Bells becomes invisible (but not the stone bar holding the bell!). Beds are invisible. 
I think you get the idea about what kind of blocks this affects. 

These items do not *remain* invisible. They eventually load back. And if you do a block update like place a block next to the invisible bugged block, they reappear. 

The bugged chest are functional. The problem is just that they lose their content.

**Comment by toad-dev** [comment]
I am able to reproduce this and have some clue about what the cause is, but I have no idea how to fix it.

In the debugger I can see that it's the DataFixer system that is wiping out block entity data. The nbt tag comes in properly formed for 1.17, passes through DFU, and, if the chunk contained a computer, comes out with no block entity data at all. In 1.18 there is a DataFix rule, `ChunkRenamesFix`,  that changes the NBT structure of chunks around quite a bit and I would have to assume this is the cause, but I don't know why _our_ block entities would be uniquely affected.

Unfortunately I was also was able to reproduce this bug on forge w/ CC: Tweaked.

**Comment by SquidDev** [comment]
Is it expected that worlds are upgradable under Fabric? I know with Forge that as of 1.13 (and the introduction of DFU) they've stated it's not really feasible.

**Comment by toad-dev** [comment]
> Is it expected that worlds are upgradable under Fabric?

It looks like Fabric itself gives no guarantees, but I did find a [community mod
](https://github.com/apple502j/UpdateBlockEntity) that tries to fix this [specific issue](https://bugs.mojang.com/browse/MC-241670).

@GreedyTactician if you have a pre-upgrade backup of your world, you could try loading it in 1.18 with the above mod active and see what happens.

**Comment by AmbitiousAlan** [comment]
It works! You are a legend! Thank you!

On an unrelated note, some mod that adds a variety of blocks decided to change block IDs of some blocks. This caused some of their blocks to disappear.
Do you know how I could fix that?
Is there a way I can see all the block IDs that a particular mod adds (without looking at them one by one in Roughly Enough Items)?
Is there a way to modify the block IDs in the save outside of minecraft?

Don't worry if you can't provide answers for the above. I just figured you are a modder so maybe you could point me to some information/resources that could help.

**Comment by Merith-TK** [comment]
sadly I do not know about that, a mod should be addative rather than subtractive in nature, I would reccomend asking the devs of those mods instead,
