### ISSUE TITLE
Server Crash when turtle attempts to handle item with NBT data

### ISSUE THREAD

**Issue by vivvyinks** [cc-tweaked/cc-restitched#50]
### Minecraft Version

1.18.x

### Version

1.99.1

### Details

[crash-2021-12-30_13.21.46-server.txt](https://github.com/cc-tweaked/cc-restitched/files/7794672/crash-2021-12-30_13.21.46-server.txt)
Server hard shut down when I tried to put an item with NBT data into an inventory management system.

Steps: start up a fabric 1.18.1 server with CC:Restitched on it, load [artist](https://github.com/SquidDev-CC/artist), following the setup steps (place an advanced turtle, add inventories, hook the turtle to the inventories) and stick anything that's got metadata (damage, NBT, etc) in the turtle once artist is running. Should produce an immediate crash.

**Comment by toad-dev** [comment]
This issue was addressed in 93b45bffed67e1b318921ad40a8e889f488caa66. Can you test [the latest release](https://github.com/cc-tweaked/cc-restitched/releases/tag/v1.18.x-1.100.0-rc.1-ccr) and see if it solves your issue?

**Comment by vivvyinks** [comment]
This fixed it, thanks for such a quick fix!
