### ISSUE TITLE
Invalid config causes crash (+ Shutdown Failure)

### ISSUE THREAD

**Issue by AnEthernetCable** [cc-tweaked/cc-restitched#52]
### Minecraft Version

1.18.x

### Version

v1.100.0 for Minecraft 1.18.x

### Details

In the event `.minecraft/config/computercraft-client.toml` is invalid (See below for testing example), Minecraft both fails to start and fails to shutdown properly. See attached `latest.log` for details.

Detecting an invalid configuration and replacing it with the default config should fix this bug.

[computercraft-client.toml.zip](https://github.com/cc-tweaked/cc-restitched/files/7818444/computercraft-client.toml.zip) (Apologies for zip, GitHub does not permit `.toml` uploads)
[latest.log](https://github.com/cc-tweaked/cc-restitched/files/7818431/latest.log)
.

**Comment by Merith-TK** [comment]
Can you confirm if this is still an issue?

**Comment by Merith-TK** [comment]
closed due to stale
