### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by TrikiNya** [cc-tweaked/cc-restitched#56]
It fixes a bug where you crash if you try to drag and drop a file. I'd suggest porting it
![image](https://user-images.githubusercontent.com/52202914/150655889-e24ff573-0595-4170-96fa-c88711ff00f9.png)

**Comment by toad-dev** [comment]
Are you saying a crash _does_ occur on CC: Restitched when dragging and dropping, or just that the version number is outdated and that is what has changed?

**Comment by toad-dev** [comment]
I can't reproduce a crash when uploading files. If you're just reporting that the version number is different than CC: Tweaked, then you should know that our "patch" version numbers (the last of three) don't necessarily align with CC: Tweaked.

**Comment by Merith-TK** [comment]
> It fixes a bug where you crash if you try to drag and drop a file. I'd suggest porting it ![image](https://user-images.githubusercontent.com/52202914/150655889-e24ff573-0595-4170-96fa-c88711ff00f9.png)

CC:R's versioning, while we try to be as close to CC:T, is NOT 1:1. 
while we try to be as close to 1:1 as possible, things such as fabric specific bugs and work arounds make that impossible

so we can only be 1:1 on the Major Releases (`X.X`), not the bugfix releases (`y.y.X`)

if yo notice a bug/feature that is present in fabric, that is NOT in CC:T, let us know.
