### ISSUE TITLE
How to make a peripheral mod with this using gradle?

### ISSUE THREAD

**Issue by samuelh2005** [cc-tweaked/cc-restitched#57]
This isn't and issue. It probably should belong in [discussions ](https://github.com/cc-tweaked/CC-Tweaked/discussions/1029)which we do not have enabled. I have reposted from the CC-Tweaked's discussions as I many get more of a response from here.

I can do this in a Forge Architectury mod to include CC Tweaked
```java
repositories {
    maven {
        url 'https://squiddev.cc/maven/'
        content {
            includeGroup 'org.squiddev'
        }
    }
}

dependencies {
    ...
    modImplementation "org.squiddev:cc-tweaked-${rootProject.minecraft_version}:${rootProject.cct_version}"
}
```

How what I would change to use CC-Restitched in my Fabric Architectury mod.
Also Architectury makes me need to use ```modImplementation``` instead of ```implementation fg.deobf```(fabric  gradle definition)

Also Architectury allows me to make my mod work on forge and fabric, by allowing to have a common code base between forge and fabric. But both forge and fabric needs to use specific libraries for the particular version.

**Comment by Merith-TK** [comment]
https://github.com/Toad-Dev/cc-peripheral-test

This is the example mod made by ToadDev! all this shows is how to register a block as peripheral, defining lua functions for said peripheral, and how to register it to a turtle! (turtle example uses the block item it self to render on the turtle so keep that in mind)

**Comment by samuelh2005** [comment]
Thank You
