### ISSUE TITLE
[1.18.2] [Causes Crash] FabricBlockSettings.breakByHand removed from Fabric API

### ISSUE THREAD

**Issue by iiisak** [cc-tweaked/cc-restitched#65]
Hello! 
I was trying to run CC:Restitched mod on Fabric 1.18.2 but it crashed Minecraft once loaded. 
I read through the error and noticed: 
```
java.lang.NoSuchMethodError: 'net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings.breakByHand(boolean)'
```
Doing some research it turns out that a relatively recent [commit](https://github.com/FabricMC/fabric/commit/d882b91555c07d52162a0b64bcbd551d193325f3) to the FabricAPI removed `FabricBlockSettings.breakByHand` which prevents CC:Restitched from working.

---
Minecraft version: 1.18.2
CC-Restitched version: 1.100.2

[latest.log](https://github.com/cc-tweaked/cc-restitched/files/8225457/latest.log)
[crash-2022-03-10_17.34.34-client.txt](https://github.com/cc-tweaked/cc-restitched/files/8225461/crash-2022-03-10_17.34.34-client.txt)

**Comment by Patbox** [comment]
Could you try using this version? 
https://github.com/cc-tweaked/cc-restitched/suites/5501390720/artifacts/176011707

Download it, open zip and copy file with shortest name to your mods folder (removing previous version ofc)

**Comment by iiisak** [comment]
Well, it seems like Minecraft is not crashing anymore. When I try to create and load a new world it seems to freeze though. I am unsure if this is related to CC:Tweaked or some other mod. Thanks!

**Comment by Merith-TK** [comment]
new release has been made for this issue
