### ISSUE TITLE
Turtle takes ~10 seconds to mine with a Diamond Pickaxe.

### ISSUE THREAD

**Issue by GravityCY** [cc-tweaked/cc-restitched#68]
The title pretty much explains everything.

No other mods installed. Just CC:R
A Computer also takes around ~3 seconds to mine with a Diamond Pickaxe.

- Fabric Version (Idk if it matters): 0.13.3
- Minecraft version: 1.18.2
 - CC: Restitched version: v1.100.3

**Comment by Merith-TK** [comment]
Could you please send logs, what code you are trying to run on the turtle

also computers cant mine, so don't know what your talking about there, only turtles can use tools

can you tell me how much ram you are giving Minecraft? 2 gigs is barely enough for vanilla in single player, most often you need to give Minecraft either 2.5gigs for a single player world on vanilla on lower end machines, 

also we do have a template for issues that does need to be filled out... that it is visible you chose not to

**Comment by GravityCY** [comment]
Clarification: Me as the player equipping a tool such as a Diamond Pickaxe trying to mine the turtle takes around ~10 seconds eg. like when mining an obsidian block as THE PLAYER takes ~10 seconds. I don't think logs are necessary, cause there's nothing that really happens it's just that for some reason the turtles/computers block hardness is insanely high or something. If you really deem logs necessary then I will.

Code: I'm not trying to run anything, I literally just can't mine the turtle with a diamond pickaxe me as the player.
RAM: 6gb

Template: Didn't I use the template but just remove some things I found not necessary? if you guys don't like that Sorry, first time posting. Like alot of looked like comments so I just removed em

**Comment by Merith-TK** [comment]
no worries, thanks for the clearification, will look into it, turtles should mimic the properties of stone for the most part, computers mimic the properties of glass, but with the sound and durability of stone

**Comment by GravityCY** [comment]
Edit: Seems like maybe everything is affected like this.

I don't know if it's worth saying but the full wired modems are also affected by this.

**Comment by Patbox** [comment]
Ah, looks like it wasn't added to required tags. Should be a simple fix
