### ISSUE TITLE
Computers are crafted with cobblestone instead of stone

### ISSUE THREAD

**Issue by SquidDev** [cc-tweaked/cc-restitched#7]
## Useful information to include:
 - Minecraft version: 1.17.1
 - CC: Restitched version: 43ef36fa15bc65d358b9ae8a74159583fba13e65

Computers can only be crafted with cobblestone rather than normal stone. This is because the `c:stone` tag contains cobblestone:

https://github.com/cc-tweaked/cc-restitched/blob/43ef36fa15bc65d358b9ae8a74159583fba13e65/src/main/resources/data/c/tags/items/stones.json#L4-L7

Compare this with Forge's stone list:

https://github.com/MinecraftForge/MinecraftForge/blob/9e476551be4649c35881c103748f3bdc3ca3b353/src/generated/resources/data/forge/tags/items/stone.json#L4-L11

**Comment by Merith-TK** [comment]
Feel Free to push a commit to fix this to match tweaked

**Comment by Merith-TK** [comment]
Fixed #20
