### ISSUE TITLE
Connecting Turtle to Modem Network gives it a "computer_x" Address

### ISSUE THREAD

**Issue by GravityCY** [cc-tweaked/cc-restitched#74]
# In CC:T this would have the address "turtle_x"

![image](https://user-images.githubusercontent.com/49225419/159517983-dab9bb17-f2c4-4b64-a6dd-4417ee9c7e2a.png)

## Useful information to include:
 - Minecraft version: 1.18.2
 - CC: Restitched version: 1.100.4

**Comment by Merith-TK** [comment]
Will have the guy maintaining the up to date version look into it,

**Comment by Merith-TK** [comment]
could you test with this?
https://github.com/cc-tweaked/cc-restitched/actions/runs/2059936303

**Comment by GravityCY** [comment]
Seems like it works, perfect! :D
