### ISSUE TITLE
[Feature] Support Tech Reborn Energy API

### ISSUE THREAD

**Issue by Merith-TK** [cc-tweaked/cc-restitched#8]
Allow turtles to be powered by a "energy", via a tech reborn battery used as a peripheral attachment or other mods

https://github.com/TechReborn/Energy

**Comment by Merith-TK** [comment]
potential implementation to get atleast TR batteries to work
```lua
function move() {
  if peripheral.isPresent("techreborn:battery") then -- Using that item id as placeholder for this
    local  fuel = turtle.getFuelLevel()
    if fuel == 0 then
      -- Subtract 1 point of energy from battery
      -- Add 1 point of fuel to turtle
    end
  end
  -- do vanilla-cc movement
end
```

**Comment by bobstar3233** [comment]
i believe that tech reborn needs to add lua support not the other way arround

**Comment by bobstar3233** [comment]
or do you mean like edit the NBT data to take "fuel" from the battery?

**Comment by Merith-TK** [comment]
sorta, I am more meaning interacting with the TR Power API directly to take power from a battery at a certain rate for every action,

**Comment by Merith-TK** [comment]
https://docs.siredvin.site/unlimitedperipheralworks/integrations/team_reborn_energy/
https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks

mod provides
