### ISSUE TITLE
Sound is not centered on the speaker block. (No 0.5 offset)

### ISSUE THREAD

**Issue by Shroototem** [cc-tweaked/cc-restitched#85]
- Minecraft version: 1.18.2
 - CC: Restitched version: v1.100.5
 - Detailed reproduction steps: 
![image](https://user-images.githubusercontent.com/47718633/163676103-2e3549e8-d9a0-4687-b8f4-fb46b0f92992.png)

**Comment by Shroototem** [comment]
Issue is in 3D space centered at relative [0.0, 0.0, 0.0] bottom negative coordinates. Expected sound origin is center of block [0.5, 0.5, 0.5]

**Comment by drakosoldier298** [comment]
How did you even figure this out?
looks like a lot of math

**Comment by Shroototem** [comment]
> 

I could hear the sound coming from the bottom corner of the block.

**Comment by Shroototem** [comment]
Just tested with Vanilla Minecraft... It's them, not you.
