### ISSUE TITLE
Pocket computer not tinted in full GUI

### ISSUE THREAD

**Issue by Jummit** [cc-tweaked/cc-restitched#94]
MC 1.18.2 cc93953691b2d2fd5fbff090a4ab482d62fcb054

When dying a pocket computer the item texture and the holding texture is updated, but in the opened GUI it is still yellow.

![image](https://user-images.githubusercontent.com/28286961/166136704-718bd550-2884-43cd-a782-ee84f869013d.png)

I don't know if this is different from CC-Tweaked.

**Comment by SquidDev** [comment]
Nah, this is the case in CC:T too.

**Comment by Merith-TK** [comment]
Well it's an parity thing so...
