### ISSUE TITLE
turtle.inspect() does not return tags

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [cc-tweaked/cc-restitched#98]
## Useful information to include:
 - Minecraft version : 1.18.2
 - CC: Restitched version : 1.100.5
 - Replication : Place  turtle in front of any block that has a tag and run **'local check, data = turtle.inspect() print(textutils.serialize(data))'**

The official CC Tweaked Wiki says it should return tags so i assume this is a bug???

**Comment by Merith-TK** [comment]
Could you test with the #96 pr gh-action? (the merge upstream pr)

Shouldn't affect it, but it just might

**Comment by Terandox-The-Pineapple** [comment]
I tested with #96 pr gh-action and it worked 👍
Will #96 be merged soon?

**Comment by Merith-TK** [comment]
Thats the plan as #96 (and #97 )brings in some of the more recent updates and changes over from CC:T

**Comment by Terandox-The-Pineapple** [comment]
Then I'm looking forward to it when the time comes.
I have temporarily installed #96 on my Minecraft server until the update comes.
I thank you for the help and have a nice day .

**Comment by SquidDev** [comment]
This should now be fixed.
